### PR TITLE
Update version of psr/log to be compatible with Drupal 8

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @totten @megaphonejon

I have run the phpunit tests and they appear to pass sensibly.

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
Thanks Seamus.  I tried doing the PR for `civicrm-core` but it looks like it wants this one done first.

I'm not super-savvy on the Packagist ecosystem.  This came up because Drupal 8.6.4 requires psr/log 1.1.0.  By specifying the same are we potentially causing a dependency conflict for other packages that require 1.0.x?  Or is this best practice?

**Comment by mlutfy** [comment]
I'm also using this in production, and could not find a way around it.

Could the dependency be more flexible? Does psr/log have many breaking changes?

**Comment by MegaphoneJon** [comment]
There are only three commits since 1.0.2.  [One is NFC](https://github.com/php-fig/log/pull/53), [one only affects tests](https://github.com/php-fig/log/pull/54).  The [last one](https://github.com/php-fig/log/pull/57) defines a test logger.

**Comment by totten** [comment]
Agree this should be relaxed to support any psr/log 1.x version.

I'd expect future psr/log updates within 1.x to be as thoughtful/upgrade-safe as the ones @MegaphoneJon pointed out.

Merged manually and relaxed the composer.json change a bit: 5a142bc4d24b7f8c830f59768b405ec74d582f22

**Comment by totten** [comment]
@seamuslee001 The updated version is tagged as v0.19.01.08

**Pull request merged**
